eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9093
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]': 
            allowedOrigins:
              - "http://localhost:3000" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" # Allow all headers
            allowCredentials: true # Allow cookies/authentication

      mvc:
        routes:
          - id: user-service
            uri: lb://AccessGrand
            predicates:
              - Path=/api/v1/**
          - id: project-task-service
            uri: lb://Taskservice
            predicates:
              - Path=/api/v2/**
          - id: Notification-service
            uri: lb://Notificationservice
            predicates:
              - Path=/notifications/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true